# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161211_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
    ]
