# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_designer_promoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='avatar',
            field=models.ImageField(default=b'default profile pic.jpg', upload_to=b'static/main/avatars/'),
        ),
    ]
